### ISSUE TITLE
Doesn't work with perl version 5.26

### ISSUE THREAD

**Issue by Shallowmallow** [FestCat/festcat-voice-builder#3]
Building the voice doesn't work with perl version 5.26

here's the explanantion of the issue http://blogs.perl.org/users/ryan_voots/2017/04/trials-and-troubles-with-changing-inc.html

A quiick workaround is to just add this line
`
use lib '.';`  at the beginning of Training.pl

**Comment by zeehio** [comment]
Thanks!

I hope it is fixed now :-)
